# Generated by Django 5.0.7 on 2025-07-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_transaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(default='', help_text='Snapshot of the product name at time of transaction', max_length=100),
            preserve_default=False,
        ),
    ]
