# Generated by Django 5.0.7 on 2025-07-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_transaction_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(default='', help_text='Snapshot of the product name at time of transaction', max_length=100),
        ),
    ]
